title: Page for GH Pages intro
author: Daniil Kutyavin
email: daniil.kutyavin94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a page for learning

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
